Disable multi-threading. It doesn't work reliably for exonerate-server, and is of limited utility for the exonerate client. Keeping the vestiges of the multi-threading code for now.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -623,7 +623,6 @@ ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
-use_pthreads
 installed_util_list
 codegen_extra_ldadd
 codegen_extra_sources
@@ -734,7 +733,6 @@ enable_gcov
 enable_largefile
 enable_compiledmodels
 enable_utilities
-enable_pthreads
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1391,9 +1389,6 @@ Optional Features:
 
   --enable-utilities Install all utilities
   --disable-utilities Do not install utilities
-
-  --enable-pthreads Use pthreads for exonerate-server
-  --disable-pthreads Do not use pthreads for exonerate-server
 
 Some influential environment variables:
   CC          C compiler command
@@ -4686,28 +4681,28 @@ else
 fi
 
 
-# ALLOW DISABLING OF PTHREADS
-# Check whether --enable-pthreads was given.
-if test "${enable_pthreads+set}" = set; then :
-  enableval=$enable_pthreads; enable_pthreads="$enableval"
-else
-  enable_pthreads=yes
-fi
-
-if test "$enable_pthreads" = yes; then
-    echo "Using PTHREADS"
-    CFLAGS="$CFLAGS -DUSE_PTHREADS"
-    # for g_thread_init()
-    g_thread_init_ldflags=`pkg-config --libs gthread-2.0`
-    LDFLAGS="$LDFLAGS $g_thread_init_ldflags -lpthread"
-elif test "$enable_pthreads" = no; then
-    echo "Not using pthreads"
-else
-    echo "error: must be yes or no:"
-    echo "    --enable-pthreads:$enable_pthreads"
-    exit 1
-fi
-
+# 2012-01-20 (nathanweeks): Disable pthreads code due to reliability issues &
+# limited utility.
+## ALLOW DISABLING OF PTHREADS
+#AC_ARG_ENABLE(pthreads,
+#[
+#  --enable-pthreads Use pthreads for exonerate-server
+#  --disable-pthreads Do not use pthreads for exonerate-server],
+#[enable_pthreads="$enableval"],[enable_pthreads=yes])
+#if test "$enable_pthreads" = yes; then
+#    echo "Using PTHREADS"
+#    CFLAGS="$CFLAGS -DUSE_PTHREADS"
+#    # for g_thread_init()
+#    g_thread_init_ldflags=`pkg-config --libs gthread-2.0`
+#    LDFLAGS="$LDFLAGS $g_thread_init_ldflags -lpthread"
+#elif test "$enable_pthreads" = no; then
+#    echo "Not using pthreads"
+#else
+#    echo "error: must be yes or no:"
+#    echo "    --enable-pthreads:[$enable_pthreads]"
+#    exit 1
+#fi
+#AC_SUBST(use_pthreads)
 
 echo "----------------------------------------------------------------"
 
